name: BlogAPI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Start Docker
      run: docker-compose up -d
    - name: Copy .env
      run: docker-compose run laravel.test php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: docker-compose run laravel.test composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs 
    - name: Generate key
      run: docker-compose run laravel.test php artisan key:generate
    - name: Directory Permissions
      run: docker-compose run laravel.test chmod -R 777 storage bootstrap/cache
    - name: Run tests
      run: docker-compose run laravel.test vendor/bin/phpunit
